### ISSUE TITLE
Retain the option to use WordNet

### ISSUE THREAD

**Issue by AlienKevin** [DefunctLizard/thesaurus-rs#1]
**Hi, could you please retain the option to use the WordNet database?** Maybe adding an enum to choose between the two databases. I found that the new moby thesaurus is too loose in its definition of synonyms for my use case. I'm creating a search algorithm that fallbacks to synonyms when the query is not found. And moby's database has many synonyms that are quite distant in meaning to the queried word, which can potentially produce undesirable results.
For example, fantastic has 200 synonyms in moby, including words like foolish which I find to have quite a different meaning, as well as words like dream-built which is rarely used and likely not present in my database in the first place.
Thanks for developing this awesome library!

**Comment by grantshandy** [comment]
Of course I can add this, and thanks for using it!

I'll add it today, and get back to you when I complete it and push a new version.

**Comment by grantshandy** [comment]
Here you go! A new version with features to turn on for both moby and wordnet.

https://docs.rs/thesaurus/latest/thesaurus/index.html

https://crates.io/crates/thesaurus

**Comment by AlienKevin** [comment]
@grantshandy Thanks for your swift update! The [Backend Comparison](https://docs.rs/thesaurus/latest/thesaurus/index.html#backend-comparison) table which lists the binary size and number of synonyms is especially helpful. Though I'm wondering whether the Compressed Dictionary Size of Moby is the same as the Simple Example Binary Size (Stripped)? In other words, the compression doesn't help at all in the case of Moby? Besides that, everything looks awesome. I'll update my package tomorrow to use the latest version. Thanks again for your help.

**Comment by grantshandy** [comment]
Thanks for your response!

The way the library works is that it takes a plain text file, compresses it (using gzip), then embeds it into the binary. The compression steps look like this for moby:

1. simple plain text file containing synonyms - **24M**
2. gzip compression - **11M**
3. embed into binary (add the size of the actual program running it) - **15M**
4. strip binary of debug symbols (using the `strip` command line program) - **11M**

The difference between the _compressed dictionary size_ and the _example binary size_ is that the binary size is the size of the program built at the end. I included the size of the stripped binary because people often do that to their programs to make them smaller.

**Comment by AlienKevin** [comment]
That makes sense, got it.
